(executables
 (names
  e01_semantics_sprint
  e02_recursion_under_pressure
  e03_lists_and_library
  e04_tail_recursion_and_shape
  e05_records_options_and_dates
  e06_variants_and_patterns
  e07_functions_and_dataflow)
 (modules
  e01_semantics_sprint
  e02_recursion_under_pressure
  e03_lists_and_library
  e04_tail_recursion_and_shape
  e05_records_options_and_dates
  e06_variants_and_patterns
  e07_functions_and_dataflow)
 (libraries unix)
 (flags (:standard -w +a-32-34-37-39-52-60-69 -warn-error -A)))

(executable
 (name e08_base_and_ppx)
 (modules e08_base_and_ppx)
 (libraries base stdio)
 (preprocess
  (pps ppx_jane))
 (flags (:standard -w +a-4-32-34-37-39-40-42-52-60-66-69-70 -warn-error -A)))

(executable
 (name e09_modules_and_interfaces)
 (modules e09_modules_and_interfaces)
 (libraries base stdio)
 (flags (:standard -w +a-32-34-37-39-52-60-69 -warn-error -A)))

(executables
 (names
  e10_persistent_data_structures
  e11_hashing_and_graphs
  e12_specs_errors_and_invariants
  e14_proofs_and_types
  e15_mutation_and_performance
  e16_sequences_and_laziness
  e18_parsing_and_interpreters
  e19_type_inference)
 (modules
  e10_persistent_data_structures
  e11_hashing_and_graphs
  e12_specs_errors_and_invariants
  e14_proofs_and_types
  e15_mutation_and_performance
  e16_sequences_and_laziness
  e18_parsing_and_interpreters
  e19_type_inference)
 (libraries core)
 (preprocess
  (pps ppx_jane))
 (flags (:standard -w +a-4-32-34-37-39-40-42-52-60-66-69-70 -warn-error -A)))

(library
 (name e13_expect_quickcheck_and_coverage)
 (modules e13_expect_quickcheck_and_coverage)
 (libraries core base_quickcheck)
 (preprocess
  (pps ppx_jane))
 (inline_tests)
 (flags (:standard -w +a-4-32-34-37-39-40-42-52-60-66-69-70 -warn-error -A)))

(executable
 (name e17_async_and_pipes)
 (modules e17_async_and_pipes)
 (libraries async)
 (preprocess
  (pps ppx_jane))
 (flags (:standard -w +a-4-32-34-37-39-40-42-52-60-66-69-70 -warn-error -A)))

(executable
 (name e20_command_and_io)
 (modules e20_command_and_io)
 (libraries async core_unix.command_unix)
 (preprocess
  (pps ppx_jane))
 (flags (:standard -w +a-4-32-34-37-39-40-42-52-60-66-69-70 -warn-error -A)))
